### ISSUE TITLE
Onchange

### ISSUE THREAD

**Issue by Gideon877** [vtrev/matching-days#1]
Hi Vusi,

Your matching days code looks good. There are two slight issues you need to fix. 
Make sure that whenever you select a date you can see the day you selected regardless of the other day. And make sure that whenever you clear one date, the color should be cleared also.

@vtrev 
@avermeulen

**Comment by avermeulen** [comment]
Thanks Thabang. That’s a good observation.

André

**Comment by vtrev** [comment]
@Gideon877  @avermeulen  Fixed! Thanks.
